# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb2208acc69538501ea8a04dd86990f338261da3139d7d75d1e91138f03083f20cd56ff96ad20960806afe49dd4e3c53eb614e9898fe77d319ec05276c55a11e

test:
  secret_key_base: a250b7965ab5c7975d7b1be020ccaa17cbd2bc46d4a935af7aca7b8c85c858f2695c1ec23c4c2c5651d606fe0673bf28d70087bc376e56c936a3f3c4d965f150

# Do not keep production secrets in the repository,
# instead read values from the environment.
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  linkedin_client: <%= ENV['LINKEDIN_AUTH_TOKEN'] %>
  linkedin_secret: <%= ENV['LINKEDIN_AUTH_SECRET'] %>
